### ISSUE TITLE
License

### ISSUE THREAD

**Issue by borkdude** [babashka/obb#1]
For nbb, babashka and scittle I've chosen the EPL 1.0 specifically, to be compatible with Clojure, since they can contain clojure sources. If you don't mind, I would like to change the license of this project to EPL 1.0 for this reason.

**Comment by zane** [comment]
Sounds good! Was already planning on doing so.

**Comment by zane** [comment]
See 3f8ef8c2bf1da9ddebd0b9cbb0f0d133b136d1fe.
