### ISSUE TITLE
Package structure

### ISSUE THREAD

**Issue by borkdude** [babashka/obb#2]
Babashka and nbb have the following package structure:

<project-name>.main for the CLI namespace
<project-name>.impl.* for non public stuff

For consistency I suggest we move `io.zane.obb` to `obb.main` and `io.zane.obb.sci` to `obb.impl.sci`.

**Comment by zane** [comment]
See b8751faed33b1178816f060dbd5e19fb86ecfea5, ccd5be52ba79355b59fdeda427ed4d5cac4b6136.
