### ISSUE TITLE
Figure out how to distribute internal library code in the brew package

### ISSUE THREAD

**Issue by borkdude** [babashka/obb#24]
See #23

**Comment by willcohen** [comment]
As this develops, I'll try to make sure the nixpkgs derivation works too!

**Comment by borkdude** [comment]
@willcohen Already merged to main. Still have to release a new brew package but we'll do that once we have actual new things to release. Let me know if you have any questions.

**Comment by willcohen** [comment]
Ah -- I see it now! Seems good for now, will deal with it pending a new release too!
